version: '3.8'
services:
  keycloak_db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADRESS_FORWARDING: "true"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    volumes:
      - ./auth/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      - ./auth/theme:/opt/jboss/keycloak/themes/ec
    expose:
      - 8080
    ports:
      - 9990:9990
      - 9001:8080
    depends_on:
      - keycloak_db
    labels:
      - "traefik.http.routers.osprey.rule=Host(`modules.${DEVELOPER}.ecdev.site`)"

volumes:
  keycloak_db_data:
